[tox]
minversion = 4.56.2
envlist = py313, lint, mypy
isolated_build = true

[gh-actions]
python =
    3.13: py313, mypy, lint

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
extras = dev
commands =
    pytest --basetemp={envtmpdir}

[testenv:lint]
basepython = python3.13
deps =
    black==26.5.1
    ruff==0.15.22
commands =
    ruff check src tests
    black --check src tests

[testenv:mypy]
basepython = python3.13
extras = dev
commands = mypy src
